name       : mxml
version    : 2.11
release    : 3
source     :
    - https://github.com/michaelrsweet/mxml/releases/download/v2.11/mxml-2.11.tar.gz : aaf68aac637dd06ba73ae5bb0537a3c4e89ca86f8c09a2d806a1f5b937e2ba8f
license    : LGPL-2.0
component  : programming
summary    : Mini-XML is a small XML parsing library that you can use to read XML and XML-like data files
description: |
    Mini-XML is a small XML parsing library that you can use to read XML and XML-like data files
setup      : |
    %configure --enable-shared
build      : |
    %make
install    : |
    %make_install BUILDROOT=$installdir
    rm -f $installdir/%libdir%/*.a
