name       : mxml
version    : 2.10
release    : 1
source     :
    - http://www.msweet.org/files/project3/mxml-2.10.tar.gz : 267ff58b64ddc767170d71dab0c729c06f45e1df9a9b6f75180b564f09767891
license    : LGPL-2.0
component  : programming
summary    : Mini-XML is a small XML parsing library that you can use to read XML and XML-like data files
description: |
    Mini-XML is a small XML parsing library that you can use to read XML and XML-like data files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install BUILDROOT=$installdir
    rm -f $installdir/usr/lib/*.a